version: "3.8"

networks:
  cybercops_default:
    driver: bridge

services:
  backend:
    image: registry.gitlab.com/cybercops_academy/cybercops_backend

  frontend:
    container_name: Frontend
    image: bayesimpact/react-base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    restart: always
    networks:
      - cybercops_default
